In [1]:
import argparse
from typing import Literal
import pandas as pd
import sys
import os
import json
from src.common.graph_loader import load_graph
from sklearn.model_selection import train_test_split
from src.common.wl_algorithms import wl_features, wl_extended_features
from copy import deepcopy
import numpy as np
from collections import Counter
from tqdm import tqdm
import random
random.seed(42)
np.random.seed(42)

In [2]:
def load_as_data() -> pd.DataFrame: #list[dict]:
    '''
    loads the algorithm selection dataset. Contains, for each datapoint:
        - the model name
        - the instance name
        - the correct label (0: chuffed better, 1: cp-sat better, 2: they are the same)
        - solving time of the chuffed solver
        - solving time of the cp-sat solver
        - the path of the corresponding graph
    '''
    data = pd.read_csv('./data/algorithm_selection_dataset.csv')
    return data

def load_p_data() -> pd.DataFrame:
    return pd.read_csv('./data/parallelise_cplex.csv')

def to_dict_p(data:pd.DataFrame) -> list[dict]:
    dict_data = []
    for i in range(len(data)):
        d = data.iloc[i]
        dict_data.append({'model': d['model'],
         'name': d['name'],
         'label': d['y'],
         'graph': './data/' + d['graph']}
        )

    return dict_data

def as_data_to_list(data:pd.DataFrame) -> list[dict]:
    dict_data = []
    for i in range(len(data)):
        d = data.iloc[i]
        dict_data.append({'model': d['model'],
         'name': d['name'],
         'label': d['label'],
         'chuffed': d['chuffed'],
         'cp-sat': d['cp-sat'],
         'graph': './data/' + d['graph']}
        )

    return dict_data

def split_stratified_by_gap(df:pd.DataFrame, rnd_state, train_size=161, test_size=40) -> tuple[pd.DataFrame, pd.DataFrame]:
    # 1. Calculate VBS and the Gap
    # VBS is the minimum PAR10 between the two solvers
    vbs = df[['chuffed', 'cp-sat']].min(axis=1)
    sbs = df['cp-sat']
    df['gap'] = sbs - vbs

    # 2. Discretize the gap into bins for stratification
    # Using 10 bins (deciles) ensures enough granularity for the split
    df['gap_strata'] = pd.qcut(df['gap'], q=8, labels=False, duplicates='drop')

    # 3. Perform the stratified split
    # 'stratify=df["gap_strata"]' ensures the gap distribution is preserved
    train_df, test_df = train_test_split(
        df,
        train_size=train_size,
        test_size=test_size,
        stratify=df['gap_strata'],
        random_state=rnd_state
    )

    # 4. Cleanup temporary columns
    for d in [train_df, test_df]:
        assert isinstance(d, pd.DataFrame), type(d)
        d.drop(columns=['gap', 'gap_strata'], inplace=True)

    assert isinstance(train_df, pd.DataFrame), type(train_df)
    assert isinstance(test_df, pd.DataFrame), type(test_df)

    return train_df, test_df

def prune(train_data:list[dict], test_data:list[dict]) -> tuple[list[dict],list[dict]]:
    train_features = np.array([t['features'] for t in train_data])
    magnitude = np.sum(train_features, axis=0)
    idxs, = np.where(magnitude <= 0)
    for t in train_data:
        t['features'] = np.array(np.delete(t['features'], idxs).tolist() + [np.sum(np.array(t['features'])[idxs])])
    for t in test_data:
        t['features'] = np.array(np.delete(t['features'], idxs).tolist() + [np.sum(np.array(t['features'])[idxs])])
    return train_data, test_data

def compute_wl_features(train_data:list[dict], test_data:list[dict], wl_type:Literal['standard','node_features','edge_features','node_edge_features'], max_iter:int) -> tuple[list[dict],list[dict]]:
    colors = {}
    MAX_COLORS = None

    for t in tqdm(train_data, desc='train data'):
        with open(t['graph']) as f:
            g = load_graph(f)
        res = wl_features(g, colors, wl_type=wl_type, max_iter=max_iter, training=True, max_colors=MAX_COLORS, with_neighbours=False)
        t['features'] = res

    colors_names = set(sorted(set(int(c) for c in colors.values())))
    for t in train_data:
        res = t['features']
        counter = Counter(res)
        n = len(res)
        features = [counter.get(color, 0) / n for color in colors_names]
        t['features'] = features

    for t in tqdm(test_data, desc='test data'):
        with open(t['graph']) as f:
            g = load_graph(f)
        res = wl_features(g, colors, wl_type=wl_type, max_iter=max_iter, training=False, max_colors=MAX_COLORS, with_neighbours=False)
        counter = Counter(res)
        n = len(res)
        features = [counter.get(color, 0) / n for color in colors_names]
        t['features'] = features

    return prune(train_data, test_data)

def compute_custom_wl(train_data:list[dict], test_data:list[dict], max_iter:int) -> tuple[list[dict],list[dict]]:
    colors = {}

    g_pairs = set()
    for t in tqdm(train_data, desc='train data'):
        with open(t['graph']) as f:
            g = load_graph(f)
        res, extra = wl_extended_features(g, colors, max_iter=max_iter, training=True)
        t['features'] = res
        t['extra'] = extra
        for pair in extra['globals_pairs'].keys():
            g_pairs.add(pair)

    g_pairs = sorted(g_pairs)

    colors_names = set(sorted(set(int(c) for c in colors.values())))
    for t in train_data:
        res = t['features']
        counter = Counter(res)
        features = np.array([counter.get(color, 0) / t['extra']['n_nodes'] for color in colors_names])
        tot_pairs = max(sum(t['extra']['globals_pairs'].values()), 1)
        t['features'] = features.tolist() + [t['extra']['globals_pairs'].get(p,0)/tot_pairs for p in g_pairs] + [t['extra']['cpv'], t['extra']['cpp']]

    for t in tqdm(test_data, desc='test data'):
        with open(t['graph']) as f:
            g = load_graph(f)
        res, extra = wl_extended_features(g, colors, max_iter=max_iter, training=False)
        counter = Counter(res)
        features = np.array([counter.get(color, 0) / extra['n_nodes'] for color in colors_names])
        tot_pairs = max(sum(extra['globals_pairs'].values()), 1)
        t['features'] = features.tolist() + [extra['globals_pairs'].get(p,0)/tot_pairs for p in g_pairs] + [extra['cpv'], extra['cpp']]

    return prune(train_data, test_data)

In [ ]:
features_type:str = 'wlc-1'
rnd_state:int = 42

data = load_as_data()

train_data, test_data = split_stratified_by_gap(data, rnd_state)
train_data, test_data = as_data_to_list(train_data), as_data_to_list(test_data)

train_data, test_data = compute_custom_wl(train_data, test_data, 1)

data loaded, starting to compute features

train data: 100%|██████████| 161/161 [02:57<00:00,  1.10s/it]
test data: 100%|██████████| 40/40 [01:36<00:00,  2.41s/it]

computed features, starting to train model

In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset

In [34]:
@torch.no_grad
def validate_model(model, dataset:DataLoader, loss) -> torch.tensor:
    running_loss = 0.

    model.eval()
    for _, (x, y) in enumerate(dataset):
        out = model(x)
        running_loss += loss(out, y)


    return running_loss/len(dataset)

In [65]:
to_one_hot = {0: [1, 0, 0], 1: [0, 1, 0], 2: [0, 0, 1]}
X_train = torch.tensor(np.array([e['features'] for e in train_data]), dtype=torch.float32)
y_train = torch.tensor(np.array([to_one_hot[e['label']] for e in train_data]), dtype=torch.float32)
times = torch.tensor(np.array([[e['chuffed'], e['cp-sat'], e['cp-sat']] for e in train_data]), dtype=torch.float32)
X_test = torch.tensor(np.array([e['features'] for e in test_data]), dtype=torch.float32)
y_test = torch.tensor(np.array([to_one_hot[e['label']] for e in test_data]), dtype=torch.float32)
n_features = X_train.shape[1]
model = nn.Sequential(
    nn.Linear(n_features, n_features),
    nn.Tanh(),
    nn.Linear(n_features, n_features * 2),
    nn.Tanh(),
    nn.Linear(n_features * 2, n_features // 2),
    nn.Tanh(),
    nn.Linear(n_features // 2, 3),
    nn.Softmax(dim=1)
)

In [66]:
train_dataloader = DataLoader(TensorDataset(X_train, y_train), batch_size=8, shuffle=True)

optimizer = torch.optim.AdamW(model.parameters(), lr=0.0001)
#scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=100, gamma=0.9)
best_loss = torch.tensor(float('inf'))
tol = torch.tensor(0.0001)
epochs_no_improve = 0
n_iter_no_change = 20

for epoch in range(15000):
        model.train()
        for i, (x, y) in enumerate(train_dataloader):
            optimizer.zero_grad()

            outputs = model(x)

            loss = F.cross_entropy(outputs, y)
            loss.backward()

            optimizer.step()

        train_loss = validate_model(model, train_dataloader, F.cross_entropy)
        
        if train_loss < best_loss - tol:
            best_loss = train_loss
            epochs_no_improve = 0
        else:
            epochs_no_improve += 1
            
        if epochs_no_improve >= n_iter_no_change:
            print()
            print(f"Convergence reached at epoch {epoch}")
            break

        print(f'\repoch: {epoch}, train loss: {train_loss:.3f}, best_loss: {best_loss:.3f}, enp: {epochs_no_improve}    ', end='\r')

epoch: 176, train loss: 0.890, best_loss: 0.778, enp: 19
Convergence reached at epoch 177

In [ ]:
from sklearn.metrics import accuracy_score
@torch.no_grad
def test_nn(clf, X_test:np.ndarray, y_test:np.ndarray, test_data:list[dict], hyperparam:dict) -> dict:
    pred = clf(X_test).argmax(dim=1)
    accuracy = accuracy_score(y_test.argmax(dim=1), pred)

    pred_time = 0
    chuffed_time = 0
    cp_sat_time_time = 0
    vbs_time = 0
    for i, e in enumerate(test_data):
        x = torch.tensor(np.array([X_test[i]]), dtype=torch.float32)
        pred = clf(x).argmax(dim=1)[0]
        if pred == 0 or pred == 2:
            pred_time += e['chuffed']
        elif pred == 1:
            pred_time += e['cp-sat']
        else:
            raise Exception(pred)
        chuffed_time += e['chuffed']
        cp_sat_time_time += e['cp-sat']
        vbs_time += min(e['chuffed'], e['cp-sat'])

    print(f"accuracy: {accuracy:.3f}")
    print(f"predicted time as a percentage of the virtual best: {pred_time/vbs_time:.3f}")
    print(f"cuffed time as a percentage of the virtual best: {chuffed_time/vbs_time:.3f}")
    print(f"cp-sat time as a percentage of the virtual best: {cp_sat_time_time/vbs_time:.3f}")
    print(f"predicted time as a percentage of the chuffed time: {pred_time/chuffed_time:.3f}")
    print(f"predicted time as a percentage of the cp-sat time: {pred_time/cp_sat_time_time:.3f}")

    return {
        'accuracy': float(accuracy),
        'clf_time': float(pred_time),
        'vbs_time': float(vbs_time),
        'chuffed_time': float(chuffed_time),
        'cp-sat_time': float(cp_sat_time_time),
        'clf_vbs': float(pred_time/vbs_time),
        'chuffed_vbs': float(chuffed_time/vbs_time),
        'cp-sat_vbs': float(cp_sat_time_time/vbs_time),
        'clf_chuffed': float(pred_time/chuffed_time),
        'clf_cp-sat': float(pred_time/cp_sat_time_time),
        'hyperparameters': hyperparam
        }

In [67]:
_ = test_nn(model, X_test, y_test, test_data, {})

accuracy: 0.600
predicted time as a percentage of the virtual best: 2.713
cuffed time as a percentage of the virtual best: 4.789
cp-sat time as a percentage of the virtual best: 3.268
predicted time as a percentage of the chuffed time: 0.566
predicted time as a percentage of the cp-sat time: 0.830

In [5]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [3]:
rnd_state:int = 74

data = load_p_data()

train_data, test_data = train_test_split(data, test_size=.2, random_state=rnd_state, stratify=data['y'])

train_data, test_data = to_dict_p(train_data), to_dict_p(test_data)

train_data, test_data = compute_custom_wl(train_data, test_data, 1)

train data: 100%|██████████| 159/159 [01:46<00:00,  1.50it/s]
test data: 100%|██████████| 40/40 [00:59<00:00,  1.48s/it]

In [33]:
X_train = np.array([e['features'] for e in train_data])
y_train = np.array([e['label'] for e in train_data])
X_test = np.array([e['features'] for e in test_data])
y_test = np.array([e['label'] for e in test_data])

scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

hyperparam = {"activation": "tanh", "alpha": 0.0001, "learning_rate": "constant", "max_iter": 15000, "solver": "adam"}

features = X_train.shape[1]
layer_sizes = (features, features * 2, features, features // 2)

clf = MLPClassifier(**hyperparam, hidden_layer_sizes=layer_sizes, random_state=rnd_state, validation_fraction=.2, early_stopping=True)

clf.fit(X_train, y_train)

MLPClassifier(activation='tanh', early_stopping=True,
              hidden_layer_sizes=(298, 596, 298, 149), max_iter=15000,
              random_state=74, validation_fraction=0.2)

In [35]:
pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, pred)

print(f"accuracy: {accuracy:.3f}")

accuracy: 0.525

In [151]:
import json
import pandas as pd
import numpy as np
from copy import deepcopy

In [152]:
with open('../parallelise_minizinc/data/results.json', 'r') as f:
    data2425 = json.load(f)
with open('../minizinc_challenge/2023_results.json', 'r') as f:
    data23 = json.load(f)

In [154]:
cplex_data = {
    '1': deepcopy(data2425['CPLEX']['1']),
    '8': deepcopy(data2425['CPLEX']['8']),
}
cplex_data['1'] += deepcopy(data23['CPLEX']['1'])
cplex_data['8'] += deepcopy(data23['CPLEX']['8'])

In [66]:
data = {'chuffed': deepcopy(data2425['chuffed']['1']), 'cp-sat': deepcopy(data2425['cp-sat']['1']), 'cplex': deepcopy(data2425['CPLEX']['1'])}
data['chuffed'] += deepcopy(data23['chuffed']['1'])
data['cp-sat'] += deepcopy(data23['cp-sat']['1'])
data['cplex'] += deepcopy(data23['CPLEX']['1'])

In [156]:
from math import floor

def scoring_function(perfs, used_alg1, used_alg2):
    _s = perfs['search']
    if _s == 'Satisfy':
        if perfs['performances'][used_alg1]['has_solution'] and not perfs['performances'][used_alg2]['has_solution']:
            return 1, 0
        elif not perfs['performances'][used_alg1]['has_solution'] and perfs['performances'][used_alg2]['has_solution']:
            return 0, 1
        else:
            ts1 = floor(perfs['performances'][used_alg1]['time'] / 1000)
            ts2 = floor(perfs['performances'][used_alg2]['time'] / 1000)
            if ts1 == ts2:
                return 0.5, 0.5
            else:
                return (ts2) / (ts1 + ts2), (ts1) / (ts1 + ts2)
    if _s == 'Minimise':
        obj1 = perfs['performances'][used_alg1]['obj']
        opt1 = perfs['performances'][used_alg1]['optimal'] == 'Optimal'
        obj2 = perfs['performances'][used_alg2]['obj']
        opt2 = perfs['performances'][used_alg2]['optimal'] == 'Optimal'
        if obj1 is None and obj2 is not None:
            assert perfs['performances'][used_alg2]['has_solution'] and not perfs['performances'][used_alg1]['has_solution']
            return 0, 1
        elif obj1 is not None and obj2 is None:
            assert perfs['performances'][used_alg1]['has_solution'] and not perfs['performances'][used_alg2]['has_solution']
            return 1, 0
        elif obj1 is None and obj2 is None:
            return 0, 0
        elif obj1 < obj2:
            return 1, 0
        elif obj2 < obj1:
            return 0, 1
        elif opt1 and not opt2:
            return 1, 0
        elif opt2 and not opt1:
            return 0, 1
        elif opt1 and opt2:
            ts1 = floor(perfs['performances'][used_alg1]['time'] / 1000)
            ts2 = floor(perfs['performances'][used_alg2]['time'] / 1000)
            if ts1 == ts2:
                return 0.5, 0.5
            else:
                return (ts2) / (ts1 + ts2), (ts1) / (ts1 + ts2)
        else:
            return 0.5, 0.5
    if _s == 'Maximise':
        obj1 = perfs['performances'][used_alg1]['obj']
        opt1 = perfs['performances'][used_alg1]['optimal'] == 'Optimal'
        obj2 = perfs['performances'][used_alg2]['obj']
        opt2 = perfs['performances'][used_alg2]['optimal'] == 'Optimal'
        if obj1 is None and obj2 is not None:
            assert perfs['performances'][used_alg2]['has_solution'] and not perfs['performances'][used_alg1]['has_solution']
            return 0, 1
        elif obj1 is not None and obj2 is None:
            assert perfs['performances'][used_alg1]['has_solution'] and not perfs['performances'][used_alg2]['has_solution']
            return 1, 0
        elif obj1 is None and obj2 is None:
            return 0, 0
        elif obj1 > obj2:
            return 1, 0
        elif obj2 > obj1:
            return 0, 1
        elif opt1 and not opt2:
            return 1, 0
        elif opt2 and not opt1:
            return 0, 1
        elif opt1 and opt2:
            ts1 = floor(perfs['performances'][used_alg1]['time'] / 1000)
            ts2 = floor(perfs['performances'][used_alg2]['time'] / 1000)
            if ts1 == ts2:
                return 0.5, 0.5
            else:
                return (ts2) / (ts1 + ts2), (ts1) / (ts1 + ts2)
        else:
            return 0.5, 0.5
    raise Exception(f"unknown search type {_s}")

In [69]:
data['chuffed'][0]

{'name': 'cstr_MODEL1507180015',
 'model': 'efm',
 'time': 1200000,
 'objective': None,
 'search': 'Minimise',
 'optimal': 'Unknown',
 'has_solution': False}

In [155]:
def reshape(data:dict[str, list[dict]]) -> dict[tuple[str,str], dict]:
    reshaped = {(d['model'], d['name']): {'performances': {}, 'search': d['search']} for d in data['chuffed']}
    for d in data['chuffed']:
        reshaped[d['model'], d['name']]['performances']['chuffed'] = {'time': d['time'], 'obj': d['objective'], 'optimal': d['optimal'], 'has_solution': d['has_solution']}
    for d in data['cp-sat']:
        reshaped[d['model'], d['name']]['performances']['cp-sat'] = {'time': d['time'], 'obj': d['objective'], 'optimal': d['optimal'], 'has_solution': d['has_solution']}
    for d in data['cplex']:
        reshaped[d['model'], d['name']]['performances']['cplex'] = {'time': d['time'], 'obj': d['objective'], 'optimal': d['optimal'], 'has_solution': d['has_solution']}
    return reshaped

In [ ]:
r = reshape(data)
s = scoring_function(r[('efm', 'cstr_MODEL1507180015')], 'cp-sat', 'chuffed')
r[('efm', 'cstr_MODEL1507180015')], s

({'performances': {'chuffed': {'time': 1200000,
    'obj': None,
    'optimal': 'Unknown',
    'has_solution': False},
   'cp-sat': {'time': 44374,
    'obj': 3,
    'optimal': 'Optimal',
    'has_solution': True},
   'cplex': {'time': 66871,
    'obj': 3,
    'optimal': 'Optimal',
    'has_solution': True}},
  'search': 'Minimise'},
 (1, 0))

In [161]:
def argmax(l:list):
    m = max(l)
    for i, _l in enumerate(l):
        if m == _l:
            return i
    raise Exception()

def where(l, f):
    for i, _l in enumerate(l):
        if f(_l):
            assert where(l[i+1:], f) == None, _l
            return _l
    return None

In [131]:
data['chuffed'][0]

{'name': 'cstr_MODEL1507180015',
 'model': 'efm',
 'time': 1200000,
 'objective': None,
 'search': 'Minimise',
 'optimal': 'Unknown',
 'has_solution': False}

In [167]:
import os
graphs = [os.path.join('graphs/', g) for g in os.listdir('data/graphs')]

In [149]:
dataset = []
#model,name,label,chuffed,cp-sat,graph
for (model, instance), v in r.items():
    scores = {a:0 for a in ['cp-sat', 'chuffed', 'cplex']}
    for a1, a2 in [('cp-sat', 'chuffed'), ('cp-sat', 'cplex'), ('cplex', 'chuffed')]:
        s1, s2 = scoring_function(v, a1, a2)
        scores[a1] += s1
        scores[a2] += s2
    label = argmax([scores['cp-sat'], scores['chuffed'], scores['cplex']])
    clean_instance = instance if instance[-1] != '_' else instance[:-1]
    model_name = model
    if 'cstr_' in clean_instance:
        clean_instance = clean_instance.replace('cstr_', '')
        model_name = model + '_cstr'
    if 'ExactlyOneSolution_' in clean_instance:
        model_name = model + '_ExactlyOneSolution'
        clean_instance = clean_instance.replace('ExactlyOneSolution_', '')
    if 'base_' in clean_instance:
        model_name = model + '_base'
        clean_instance = clean_instance.replace('base_', '')
    if 'allocation_only_' in clean_instance:
        model_name = model + '_allocation_only'
        clean_instance = clean_instance.replace('allocation_only_', '')
    if 'queens_mznc2021_' in clean_instance:
        model_name = model + '_queens_mznc2021'
        clean_instance = clean_instance.replace('queens_mznc2021_', '')
    if '.json' in clean_instance:
        clean_instance = clean_instance.replace('.json', '')
    if 'opt_' in clean_instance:
        model_name = model + '_opt'
        clean_instance = clean_instance.replace('opt_', '')
    if 'clear_cp_' in clean_instance:
        model_name = model + '_clear_cp'
        clean_instance = clean_instance.replace('clear_cp_', '')
    if '1id_' in clean_instance:
        model_name = model + '_1id'
        clean_instance = clean_instance.replace('1id_', '')
    # clean_instance = clean_instance.split('_')[-1]
    clean_model = model if model != 'is' else 'model'
    clean_model = clean_model if clean_model != 'ihtc-2024-marte' else 'model'
    try:
        graph = where(graphs, lambda x: clean_instance in x and clean_model in x)
    except Exception as e:
        print(clean_instance, instance)
        raise e
    assert graph is not None, clean_instance
    dataset.append({
        'model': model_name,
        'name': clean_instance,
        'cp-sat': scores['cp-sat'],
        'chuffed': scores['chuffed'],
        'cplex': scores['cplex'],
        'label': label,
        'graph': graph
    })

In [129]:
features = pd.read_csv('data/fzn2feat_joined.csv')

In [170]:
def clean(instance:str):
    clean_instance = instance if instance[-1] != '_' else instance[:-1]
    if 'cstr' in clean_instance:
        clean_instance = clean_instance.replace('cstr_', '')
    if 'ExactlyOneSolution_' in clean_instance:
        clean_instance = clean_instance.replace('ExactlyOneSolution_', '')
    if 'base_' in clean_instance:
        clean_instance = clean_instance.replace('base_', '')
    if 'allocation_only_' in clean_instance:
        clean_instance = clean_instance.replace('allocation_only_', '')
    if 'queens_mznc2021_' in clean_instance:
        clean_instance = clean_instance.replace('queens_mznc2021_', '')
    if '.json' in clean_instance:
        clean_instance = clean_instance.replace('.json', '')
    if 'opt_' in clean_instance:
        clean_instance = clean_instance.replace('opt_', '')
    if 'clear_cp_' in clean_instance:
        clean_instance = clean_instance.replace('clear_cp_', '')
    if '1id_' in clean_instance:
        clean_instance = clean_instance.replace('1id_', '')
    return clean_instance

In [143]:
instances = set([clean(d['name']) for d in data23['chuffed']['1']])
for inst in instances:
    if inst != 'equations_01_track_123-int':
        assert len(features[features['name'] == inst]) == 1, inst

In [150]:
d = pd.DataFrame(dataset)
d.to_csv('data/algorithm_selection_dataset_score.csv', index=None)
d

,model,name,cp-sat,chuffed,cplex,label,graph
0,efm_cstr,MODEL1507180015,1.600000,0.000000,1.400000,0,graphs/efm_cstr-sep-MODEL1507180015.graph
1,is,1vERFuvviS,1.000000,1.000000,1.000000,0,graphs/model-sep-1vERFuvviS.graph
2,ihtc-2024-marte,i03,2.000000,1.000000,0.000000,0,graphs/model-sep-i03.graph
3,word,equations_03_track_133-int,0.758621,1.898776,0.342603,1,graphs/word_equations_03_track_133-int.graph
4,black-hole,layout_3,1.000000,2.000000,0.000000,1,graphs/black-hole-sep-layout_3.graph
...,...,...,...,...,...,...,...
295,SPECK-Optimisation,easy_1,1.000000,1.000000,1.000000,0,graphs/SPECK-Optimisation-sep-easy_1.graph
296,ccmcp,3_25_0.10_2,0.941176,2.000000,0.058824,1,graphs/ccmcp-sep-3_25_0.10_2.graph
297,valve-network,horizon19,1.000000,2.000000,0.000000,1,graphs/valve-network-sep-horizon19.graph
298,chessboard,chessboard4,0.833333,2.000000,0.166667,1,graphs/chessboard-sep-chessboard4.graph
299,evmopt-generic,PlaylinkAirdrop_run_code_of_0_block_216_0_input,1.500000,1.500000,0.000000,0,graphs/evmopt-generic-sep-PlaylinkAirdrop_run_...

In [164]:
def reshape(data:dict[str, list[dict]]) -> dict[tuple[str,str], dict]:
    reshaped = {(d['model'], d['name']): {'performances': {}, 'search': d['search']} for d in data['1']}
    for d in data['1']:
        reshaped[d['model'], d['name']]['performances']['1'] = {'time': d['time'], 'obj': d['objective'], 'optimal': d['optimal'], 'has_solution': d['has_solution']}
    for d in data['8']:
        reshaped[d['model'], d['name']]['performances']['8'] = {'time': d['time'], 'obj': d['objective'], 'optimal': d['optimal'], 'has_solution': d['has_solution']}
    return reshaped

In [172]:
r_cplex = reshape(cplex_data)
s = scoring_function(r_cplex[('accap', 'accap_a8_f50_t30')], '1', '8')
r_cplex[('accap', 'accap_a8_f50_t30')], s

({'performances': {'1': {'time': 21104,
    'obj': 96,
    'optimal': 'Unknown',
    'has_solution': True},
   '8': {'time': 565466,
    'obj': 96,
    'optimal': 'Optimal',
    'has_solution': True}},
  'search': 'Minimise'},
 (0, 1))

In [ ]:
dataset = []
for (model, instance), v in r_cplex.items():
    scores = {a:0 for a in ['1', '8']}
    for a1, a2 in [('1', '8')]:
        s1, s2 = scoring_function(v, a1, a2)
        scores[a1] += s1
        scores[a2] += s2
    label = argmax([scores['1'], scores['8']])
    clean_instance = instance if instance[-1] != '_' else instance[:-1]
    model_name = model
    if 'cstr_' in clean_instance:
        clean_instance = clean_instance.replace('cstr_', '')
        model_name = model + '_cstr'
    if 'ExactlyOneSolution_' in clean_instance:
        model_name = model + '_ExactlyOneSolution'
        clean_instance = clean_instance.replace('ExactlyOneSolution_', '')
    if 'base_' in clean_instance:
        model_name = model + '_base'
        clean_instance = clean_instance.replace('base_', '')
    if 'allocation_only_' in clean_instance:
        model_name = model + '_allocation_only'
        clean_instance = clean_instance.replace('allocation_only_', '')
    if 'queens_mznc2021_' in clean_instance:
        model_name = model + '_queens_mznc2021'
        clean_instance = clean_instance.replace('queens_mznc2021_', '')
    if '.json' in clean_instance:
        clean_instance = clean_instance.replace('.json', '')
    if 'opt_' in clean_instance:
        model_name = model + '_opt'
        clean_instance = clean_instance.replace('opt_', '')
    if 'clear_cp_' in clean_instance:
        model_name = model + '_clear_cp'
        clean_instance = clean_instance.replace('clear_cp_', '')
    if '1id_' in clean_instance:
        model_name = model + '_1id'
        clean_instance = clean_instance.replace('1id_', '')
    clean_model = model if model != 'is' else 'model'
    clean_model = clean_model if clean_model != 'ihtc-2024-marte' else 'model'
    try:
        graph = where(graphs, lambda x: clean_instance in x and clean_model in x)
    except Exception as e:
        print(clean_instance, instance)
        raise e
    assert graph is not None, clean_instance
    dataset.append({
        'model': model_name,
        'name': clean_instance,
        'y': label,
        '1': scores['8'],
        '8': scores['1'],
        'graph': graph
    })

In [173]:
d = pd.DataFrame(dataset)
d.to_csv('data/parallelise_cplex.csv', index=None)
d

,model,name,y,1,8,graph
0,accap,accap_a8_f50_t30,1,1.000000,0.000000,graphs/accap-sep-accap_a8_f50_t30.graph
1,word,equations_01_track_123-int,0,0.000000,0.000000,graphs/word_equations_01_track_123-int.graph
2,efm_cstr,MODEL2204150001,1,0.697917,0.302083,graphs/efm_cstr-sep-MODEL2204150001.graph
3,hoist-benchmark,PU_2_2_3,1,1.000000,0.000000,graphs/hoist-benchmark-sep-PU_2_2_3.graph
4,triangular,n9,0,0.500000,0.500000,graphs/triangular-sep-n9.graph
...,...,...,...,...,...,...
295,ccmcp,3_20_0.40_2,1,0.895833,0.104167,graphs/ccmcp-sep-3_20_0.40_2.graph
296,Unit-Commitment,L15-T48G30L15,1,1.000000,0.000000,graphs/Unit-Commitment-sep-L15-T48G30L15.graph
297,bool-model,large,1,0.527273,0.472727,graphs/bool-model-sep-large.graph
298,Unit-Commitment,L7-T12G5L5,0,0.500000,0.500000,graphs/Unit-Commitment-sep-L7-T12G5L5.graph
299,roster_model,chicroster_dataset_large_16,0,0.500000,0.500000,graphs/roster_model-sep-chicroster_dataset_lar...